# force constants generated by Mattersim with LAMMPS
from ase.io import read
from kaldo.forceconstants import ForceConstants
from kaldo.phonons import Phonons
import kaldo.controllers.plotter as plotter
import numpy as np

# Denote supercell size for second fc and root folder

### Set up forceconstants object
# Load in computed 2nd order IFCs from LAMMPS outputs
forceconstants = ForceConstants.from_folder(folder='fc_Si46', 
                                            supercell=np.array([3, 3, 3]),  
                                            format='lammps', 
                                            only_second=True)


# Create Phonons Object
phonons = Phonons(forceconstants = forceconstants,
                  kpts = [5, 5, 5],
                  is_classic = False,
                  temperature = 300, # K
                  folder = 'ALD_Si46',
                  storage = 'numpy')

# Plot phonon dispersion
plotter.plot_dispersion(phonons,n_k_points=300, is_showing=False)

# Plot total and particial dos
plotter.plot_dos(phonons,p_atoms=None, bandwidth=0.005, filename='dos', is_showing=False)

