# force constants generated by Mattersim with LAMMPS
from ase.io import read
from kaldo.conductivity import Conductivity
from kaldo.forceconstants import ForceConstants
from kaldo.phonons import Phonons
import kaldo.controllers.plotter as plotter
import numpy as np

# Denote supercell size for second fc and root folder

### Set up forceconstants object
# Load in computed 2nd, 3rd IFCs from LAMMPS outputs
forceconstants = ForceConstants.from_folder(folder = 'fc_Si46', 
                                            supercell = np.array([3, 3, 3]), 
                                            format ='lammps')

# Establish the temperature array
temperatures = np.arange(10, 1060, 50, dtype=int)


for temperature in temperatures:

    # Create Phonons Object
    phonons = Phonons(forceconstants = forceconstants,
                kpts = [5, 5, 5],
                is_classic = False,
                temperature = temperature, # K
                folder = 'ALD_Si46',
                storage = 'numpy')

    print('\n')
    rta_cond_matrix = Conductivity(phonons=phonons, method='rta', n_iterations=0).conductivity.sum(axis=0)
    print('Thermal conductivity RTA (W/mK): %.3f'%(np.mean(np.diag(rta_cond_matrix))))
    print(rta_cond_matrix)
    
    print('\n')
    qhgk_cond_matrix = Conductivity(phonons=phonons, method='qhgk', n_iterations=0).conductivity.sum(axis=0)
    print('Thermal conductivity QHGK (W/mK): %.3f'%(np.mean(np.diag(qhgk_cond_matrix))))
    print(qhgk_cond_matrix)
