#!/bin/bash
# Runs the full Quantum Espresso calculation on 16 threads
# This took one full day on 16 cores. Please note that should your quantum espresso run's be
# interrupted, it's okay to bash this script again. It will pick up where it left off using
# the quantum espresso "recover" flag, and identifying which executables need to be run still.

# Parameters
nthreads=16
overwrite_dynamics="true"

# Begin QE
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
printf "Beginning QE calculation.\n"

# Check for frequencies
if [ ! -f "dynamics/FREQ.gp" ];
then
  printf "Frequencies have not been generated by matdyn in standard location. "
  printf "Checking cause ..\n"

  # Failed. - do we have the IFCs in real space?
  if [ ! -f "espresso.ifc2" ];
  then

    printf "\tNo real space space force constants exist.\n\n"
    printf "Checking reciprocal space force constants .."
    # Failed - do we have the IFCs in reciprocal space?
    if [ ! -f "DYN.mat12" ];
    then

      # Get self-consistent wave functions
      if [ ! -f "tmp/mono.save/data-file-schema.xml" ];
      then
        printf "\tstarting from SCF calculation.\n"
        printf "running pw.x .."
        mpirun -np $nthreads pw.x < input.scf &> output.scf
        printf "\t complete!\n\n"
      fi

      # Reaching this point implies, you need the dispersion, but have wave functions.
      printf "\n\tMissing at least one IFC matrix. Pursuing ph.x execution.\n"
      printf "\n\n\t\t!!! - Please disown this process and redirect output to a file.\n"
      printf "\t\t!!! - This could take over 20 hours.\n\n"
      mpirun -np $nthreads ph.x < input.ph &> output.ph
      printf "\tCompleted reciprocal space IFC calculation!!.\n"
    fi

    # Because we have momentum-space (reciprocal-space) FC's, fourier interpolate them
    # back to real space.
    printf "\nrunning q2r.x .."
    q2r.x < input.q2r &> output.q2r
    printf "\t complete!\n"
  fi

  # Finally, run matdyn.
  # Setup directories ..
  printf "\nRecriprocal forces have been generated/found.\n"
  printf "\nFinal stage requires setup directories. Checking .."
  if [ ! -d "dynamics" ];
  then
    mkdir dynamics
  else
    printf "\n\t\"dynamics\" directory already exists"
    if [ ${overwrite_dynamics} == "true" ];
    then
      printf " and permission was given to overwrite. Clearing directory \"dynamics\"\n"
      rm dynamics/* &> /dev/null
    else
      printf "!\n\n\t\t No permission to overwrite contents in \"dynamics\"\n"
      printf "\t\t Fatal error. matdyn.x will not overwrite, please move"
      printf "the contents of \"dynamics\" to a safe location and rerun.\n\n"
      exit 1
    fi
  fi
  printf "running matdyn.x .."
  matdyn.x < input.md  &> output.md
  printf "\t complete!\n"
fi

printf "\n\"run_qe.sh\" completed and detected a dispersion!"
printf "Phonon frequencies along chosen path are sent to \"dynamics/FREQ.gp\"\n\n"