"""Quantum ESPRESSO force-constant interfaces.

This module owns the format-specific q2r IFC2 and d3q IFC3 readers together
with the provenance-critical q2r header parser. The header retains QE's
lattice gauge, masses, Born charges, dielectric response, Ewald alpha, and
q-grid for the harmonic NAC controller.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import re
from typing import Sequence

import numpy as np
from ase import Atoms
from ase.units import Bohr, Rydberg
from numpy.typing import NDArray
from numpy.typing import ArrayLike

from kaldo.grid import Grid
from kaldo.helpers.logger import get_logger

logging = get_logger()


def read_second_order_qe_matrix(filename):
    """Read second-order force constants generated by QE ``q2r.x``.

    A true macroscopic-data flag in a polar q2r file is provenance, not merely
    optional metadata: QE ``do_q2r`` has already subtracted ``rigd_blk`` from
    every commensurate dynamical matrix before transforming it to the stored
    real-space IFC body. ``SecondOrder.load`` therefore combines this legacy
    body reader with :func:`read_q2r_header` and tags the result as
    ``dipole_subtracted_fc``; the harmonic controller must restore QE's
    matching rigid-ion term and must not perform the generic Gonze subtraction
    again.

    The original kALDo body reader and array layout are preserved. Only IFC
    values are converted from Ry/bohr² to eV/angstrom². The dimensionless
    dielectric and Born tensors remain in their native QE row/column gauge so
    the restoration reproduces ``rigid.f90`` exactly.

    Parameters
    ----------
    filename : str
        The path to file of second order force constants in Quantum Espresso format.

    Returns
    -------
        second : np.ndarray(i_at, alpha, t1, t2, t3, j_at, beta)
            The array contains second order force constants.
            alpha and beta are directional indexes in x,y,z.
            t1, t2, t3 is the index to the supercell for j-th atom.
            i_at and j_at are the indexes to the atoms as in unit cell.

        supercell : [t1, t2, t3]
            The size of the supercell as t1 * t2 * t3.

        charges : np.ndarray or None
            Legacy-compatible tensor stack: ``charges[0]`` is the electronic
            dielectric tensor and ``charges[1:]`` are the Born effective-charge
            tensors. ``None`` means the q2r macroscopic-data flag was false.
            :func:`read_q2r_header` is the authoritative source for q2r NAC
            provenance and the additional Ewald/lattice metadata.
    """
    with open(filename, "r") as file:
        # skip all the prelude info, jump to second order force constants

        # read first 3 integers in the first line: ntype, n_atoms, ibrav
        ntype, n_atoms, ibrav = [int(x) for x in file.readline().split()[:3]]

        if ibrav == 0:
            # skip 3 lines of cell parameters
            for _ in range(3):
                file.readline()
        # skip lines of types of atoms
        for _ in range(ntype):
            file.readline()
        # skip lists of atom positions
        for _ in range(n_atoms):
            file.readline()

        # Read Dielectric constant tensor if it has it
        polar = file.readline()
        if "T" in polar:
            logging.info("Charge data found in 2nd order QE file")
            charges = np.zeros((n_atoms + 1, 3, 3))
            for alpha in np.arange(3):  # Dielectric constant tensor
                charges[0, alpha, :] = file.readline().split()
            for na in np.arange(n_atoms):  # Born effective charges
                file.readline()
                for alpha in np.arange(3):
                    charges[na + 1, alpha, :] = file.readline().split()
        else:
            charges = None
            logging.warning(
                "No Born effective charges / dielectric tensor in %s (NAC flag F): "
                "the non-analytic correction is disabled. For a polar material the "
                "dispersion will lack LO-TO splitting; re-run q2r.x with zeu=.true. "
                "and epsil=.true. if NAC is needed.",
                filename,
            )

        # Read second order force constants
        # read t1*t2*t3 supercell
        supercell = [int(x) for x in file.readline().split()]
        # dimension of supercell info should be 3 as t1*t2*t3
        assert len(supercell) == 3

        second = np.zeros(
            (3, 3, n_atoms, n_atoms, supercell[0], supercell[1], supercell[2])
        )

        # there are 3 * 3 * n_atoms * n_atoms blocks of force constants
        for _i in range(3 * 3 * n_atoms * n_atoms):
            alpha, beta, i_at, j_at = [int(x) - 1 for x in file.readline().split()]

            # each block contains t1*t2*t3 force constants
            for _j in range(supercell[0] * supercell[1] * supercell[2]):
                # line format: "<t1>, <t2>, <t3>, <second order force>"
                line = file.readline().split()
                t1, t2, t3 = [int(x) - 1 for x in line[:3]]
                second[alpha, beta, i_at, j_at, t1, t2, t3] = float(line[3]) * (
                    Rydberg / (Bohr**2)
                )
        second = second.transpose(2, 0, 4, 5, 6, 3, 1)
        return second, supercell, charges


def read_third_d3q(
    filename: str,
    atoms: Atoms,
    supercell: tuple[int, int, int] | ArrayLike,
    order: str = "C",
) -> np.ndarray[tuple[int, int, int, int, int, int, int, int], np.dtype[np.float64]]:
    """Read third order d3q format.

    Parameters
    ----------
    filename : str
        The path to file of third order force constants in d3q format.

    atoms : ase.Atoms
        Primitive atoms used to determine the number of atom blocks.

    supercell : tuple[int, int, int], shape as [t1, t2, t3]
        The size of the supercell as t1 * t2 * t3.

    order : str
        Replica-grid flattening order, normally ``"C"`` for QE/d3q files.

    Returns
    -------
        third_order : np.ndarray
            The array contains third order force constants.
            alpha, beta, and gamma are directional indexes in x,y,z.
            second_cell_id is the index to the supercell for j-th atom.
            third_cell_id is the index to the supercell for k-th atom.
            atom_i, atom_j and atom_k are the indexes to the atoms as in unit cell.
    """
    # Note: d3q is similar to second order qe format.

    with open(filename, "r") as file:
        n_unit_atoms = atoms.positions.shape[0]
        n_replicas = np.prod(supercell)
        current_grid = Grid(supercell, order=order)
        supercell = np.array(supercell)

        # initalize third order force constant
        third_order = np.zeros(
            (n_unit_atoms, 3, n_replicas, n_unit_atoms, 3, n_replicas, n_unit_atoms, 3)
        )

        # read first line
        ntype, n_atoms, ibrav = [int(x) for x in file.readline().split()[:3]]

        if ibrav == 0:
            # skip 3 lines of cell parameters
            for _ in np.arange(3):
                file.readline()

        # skip lines of types of atoms
        for _ in np.arange(ntype):
            file.readline()
        # skip lists of atom positions
        for _ in np.arange(n_atoms):
            file.readline()

        # skip Dielectric constant tensor if it has
        polar = file.readline()
        if "T" in polar:
            for _ in np.arange(3):
                file.readline()
            for _ in np.arange(n_atoms):
                file.readline()
                for _ in np.arange(3):
                    file.readline()

        # next line is 3rd order supercell
        test_supercell = np.array([int(x) for x in file.readline().split()])
        # the third supercell can be different to the second one
        logging.info(
            "Important: FORCECONSTANTS_3RD must be generated by d3q without "
            "recentering. Cell indices must run from 0 to nrep, not from "
            "-nrep/2 to nrep/2."
        )
        if not np.array_equal(supercell, test_supercell):
            logging.error(
                "third supercell not consistent with 3rd Forces file: "
                f"{test_supercell} != {supercell}"
            )

        error_notation = 0
        for i in range((3 * n_unit_atoms) ** 3):
            alpha, beta, gamma, atom_i, atom_j, atom_k = (
                np.array([int(x) for x in file.readline().split()]) - 1
            )

            # skip a line
            file.readline()
            for j in range(n_replicas**2):
                readline = file.readline().split()

                second_cell_index = [int(x) for x in readline[:3]]
                third_cell_index = [int(x) for x in readline[3:6]]

                # wrap cell index
                second_cell_index -= supercell * np.rint(second_cell_index / supercell)
                third_cell_index -= supercell * np.rint(third_cell_index / supercell)

                second_cell_id = current_grid.grid_index_to_id(
                    second_cell_index, is_wrapping=True
                )
                third_cell_id = current_grid.grid_index_to_id(
                    third_cell_index, is_wrapping=True
                )

                if readline[6][-4] == "E":
                    # it has two digits for exp part
                    third_order[
                        atom_i,
                        alpha,
                        second_cell_id,
                        atom_j,
                        beta,
                        third_cell_id,
                        atom_k,
                        gamma,
                    ] = float(readline[6]) * (Rydberg / (Bohr**3))
                else:
                    third_order[
                        atom_i,
                        alpha,
                        second_cell_id,
                        atom_j,
                        beta,
                        third_cell_id,
                        atom_k,
                        gamma,
                    ] = 0.0
                    error_notation += 1

        logging.info(
            "Values below e-100 with unsupported notation were set to 0.0; "
            "this occurred %d times.",
            error_notation,
        )

        third_order = third_order.reshape(
            (
                n_unit_atoms * 3,
                n_replicas * n_unit_atoms * 3,
                n_replicas * n_unit_atoms * 3,
            )
        )
        return third_order


_FLOAT = NDArray[np.float64]
_INT = NDArray[np.int64]

# QE constants.f90 convention, verified against QE 7.6. q2r stores masses in
# electron-mass / 2 units in the Rydberg atomic-unit system.
AMU_RY = (1.66053906660e-27 / 9.1093837015e-31) / 2.0


class Q2RFormatError(ValueError):
    """A formatted QE q2r file does not have the expected header."""


def _float(value: str) -> float:
    """Parse a Fortran real token, accepting either ``D`` or ``E`` exponents."""
    return float(value.replace("D", "E").replace("d", "e"))


def _numbers(line: str) -> list[float]:
    """Extract all Fortran-readable real values from one formatted q2r line.

    Non-numeric tokens such as quoted species labels are intentionally
    ignored. This mirrors the list-directed numeric fields written by QE.
    """
    values: list[float] = []
    for token in line.replace(",", " ").split():
        try:
            values.append(_float(token))
        except ValueError:
            pass
    return values


def _next(lines: list[str], index: int) -> tuple[int, str]:
    """Return the next nonblank q2r line and its zero-based file index."""
    while index < len(lines) and not lines[index].strip():
        index += 1
    if index == len(lines):
        raise Q2RFormatError("unexpected end of q2r file")
    return index, lines[index]


def _logical(value: str) -> bool:
    """Parse a formatted Fortran logical token used by q2r header flags."""
    normalized = value.strip().strip(",").strip(".").lower()
    if normalized in {"t", "true", "1"}:
        return True
    if normalized in {"f", "false", "0"}:
        return False
    raise Q2RFormatError(f"invalid Fortran logical token {value!r}")


_TYPE = re.compile(
    r"^\s*(?P<i>[+-]?\d+)\s+(?:['\"](?P<q>[^'\"]+)['\"]|(?P<s>\S+))\s+(?P<m>[+\-0-9.eEdD]+)"
)


@dataclass(frozen=True)
class Q2RHeader:
    """Native q2r structure, Ewald data, and dipole-subtraction provenance.

    ``at_columns`` and ``tau`` retain QE's ``alat`` gauge; ``dielectric`` and
    ``born`` remain dimensionless and unmodified. When ``has_zstar`` is true,
    the associated IFC body is the analytical short-range body written after
    q2r removed ``rgd_blk`` on ``q_grid`` using ``alpha``.
    """

    path: Path
    ntypes: int
    natoms: int
    ibrav: int
    celldm: _FLOAT
    alat_bohr: float
    at_columns: _FLOAT
    cell_rows_bohr: _FLOAT
    volume_bohr3: float
    symbols: tuple[str, ...]
    type_masses_qe: _FLOAT
    type_masses_amu: _FLOAT
    atom_types: _INT
    tau: _FLOAT
    has_zstar: bool
    alpha: float
    dielectric: _FLOAT
    born: _FLOAT
    q_grid: tuple[int, int, int]
    macro_line_index: int
    qgrid_line_index: int
    body_start_line: int

    @property
    def atom_masses_amu(self) -> _FLOAT:
        """Expand type masses to one atomic-mass value per primitive atom."""
        return np.asarray(self.type_masses_amu[self.atom_types - 1], dtype=float)

    @property
    def positions_rows_bohr(self) -> _FLOAT:
        """Return primitive Cartesian positions as row vectors in bohr."""
        return np.asarray(self.tau * self.alat_bohr, dtype=float)


def read_q2r_header(path: str | Path) -> Q2RHeader:
    """Read q2r structure and NAC provenance without loading the IFC body.

    Lattice vectors and atomic positions remain in QE's native ``alat``
    convention. Masses are exposed both in the q2r Rydberg-unit convention and
    in atomic mass units. ``has_zstar=True`` records that q2r wrote an already
    dipole-subtracted IFC body. The returned line indices allow fixture tools
    to preserve that numerical body byte-for-byte.
    """
    source = Path(path)
    lines = source.read_text(encoding="utf-8", errors="strict").splitlines(
        keepends=True
    )
    index, line = _next(lines, 0)
    tokens = line.replace(",", " ").split()
    if len(tokens) < 9:
        raise Q2RFormatError(
            "first q2r line must contain ntyp, nat, ibrav, and six celldm values"
        )
    try:
        ntypes, natoms, ibrav = map(int, tokens[:3])
        celldm = np.asarray([_float(x) for x in tokens[3:9]], dtype=float)
    except ValueError as exc:
        raise Q2RFormatError("could not parse q2r cell header") from exc
    if ntypes <= 0 or natoms <= 0:
        raise Q2RFormatError("ntypes and natoms must be positive")
    index += 1
    at_input = None
    if ibrav == 0:
        at_input = np.zeros((3, 3), dtype=float)
        for column in range(3):
            index, line = _next(lines, index)
            values = _numbers(line)
            if len(values) < 3:
                raise Q2RFormatError("ibrav=0 requires three lattice-vector lines")
            at_input[:, column] = values[:3]
            index += 1
    try:
        cell, volume = qe_lattice_from_ibrav(ibrav, celldm, at_columns=at_input)
    except ValueError as exc:
        raise Q2RFormatError(str(exc)) from exc
    alat = float(celldm[0])
    at = np.asarray(cell.T / alat, dtype=float)
    symbols: list[str] = []
    masses = np.empty(ntypes, dtype=float)
    for expected in range(1, ntypes + 1):
        index, line = _next(lines, index)
        match = _TYPE.match(line)
        if match is None or int(match.group("i")) != expected:
            raise Q2RFormatError(f"could not parse atomic-type line {expected}")
        symbol = (match.group("q") or match.group("s") or "").strip()
        # q2r accepts blank quoted labels and the original IFC reader never
        # depended on them. Preserve that valid legacy input; masses and atom
        # type indices, not labels, define the NAC metadata.
        symbols.append(symbol)
        masses[expected - 1] = _float(match.group("m"))
        index += 1
    atom_types = np.empty(natoms, dtype=np.int64)
    tau = np.empty((natoms, 3), dtype=float)
    for expected in range(1, natoms + 1):
        index, line = _next(lines, index)
        values = line.replace(",", " ").split()
        if len(values) < 5:
            raise Q2RFormatError(f"could not parse atom line {expected}")
        try:
            observed, kind = int(values[0]), int(values[1])
            coordinate = [_float(x) for x in values[2:5]]
        except ValueError as exc:
            raise Q2RFormatError(f"could not parse atom line {expected}") from exc
        if observed != expected or not 1 <= kind <= ntypes:
            raise Q2RFormatError(f"invalid atom line {expected}")
        atom_types[expected - 1] = kind
        tau[expected - 1] = coordinate
        index += 1
    index, line = _next(lines, index)
    macro_index = index
    values = line.replace(",", " ").split()
    if not values:
        raise Q2RFormatError("missing q2r macroscopic-data flag")
    has_zstar = _logical(values[0])
    alpha = 1.0
    if len(values) > 1:
        try:
            alpha = _float(values[1])
        except ValueError:
            alpha = 1.0  # QE legacy one-field fallback
    if not np.isfinite(alpha) or alpha <= 0:
        raise Q2RFormatError("Ewald alpha must be finite and positive")
    index += 1
    dielectric = np.zeros((3, 3))
    born = np.zeros((natoms, 3, 3))
    if has_zstar:
        for row in range(3):
            index, line = _next(lines, index)
            values = _numbers(line)
            if len(values) < 3:
                raise Q2RFormatError("dielectric tensor is incomplete")
            dielectric[row] = values[:3]
            index += 1
        for expected in range(1, natoms + 1):
            index, line = _next(lines, index)
            try:
                observed = int(line.split()[0])
            except (IndexError, ValueError) as exc:
                raise Q2RFormatError("invalid Born-charge atom marker") from exc
            if observed != expected:
                raise Q2RFormatError(
                    f"Born tensor atom index {observed} encountered where {expected} was expected"
                )
            index += 1
            for row in range(3):
                index, line = _next(lines, index)
                values = _numbers(line)
                if len(values) < 3:
                    raise Q2RFormatError(
                        f"Born tensor for atom {expected} is incomplete"
                    )
                born[expected - 1, row] = values[:3]
                index += 1
    index, line = _next(lines, index)
    grid_index = index
    values = line.replace(",", " ").split()
    if len(values) < 3:
        raise Q2RFormatError("q2r FFT-grid line must contain nr1, nr2, nr3")
    try:
        grid = tuple(int(x) for x in values[:3])
    except ValueError as exc:
        raise Q2RFormatError("could not parse q2r FFT grid") from exc
    if any(x <= 0 for x in grid):
        raise Q2RFormatError(f"q2r FFT grid must be positive, got {grid}")
    return Q2RHeader(
        source,
        ntypes,
        natoms,
        ibrav,
        celldm,
        alat,
        at,
        cell,
        volume,
        tuple(symbols),
        masses,
        masses / AMU_RY,
        atom_types,
        tau,
        has_zstar,
        alpha,
        dielectric,
        born,
        grid,
        macro_index,
        grid_index,
        index + 1,
    )


def strip_q2r_nac(source: str | Path, destination: str | Path) -> Path:
    """Copy a q2r file while disabling its macroscopic NAC header.

    The lattice, q grid, and IFC body are retained. Only the dielectric and
    Born-charge block is removed and its flag is replaced by ``F``.
    """
    header = read_q2r_header(source)
    source_path, target = Path(source), Path(destination)
    lines = source_path.read_text(encoding="utf-8").splitlines(keepends=True)
    output = (
        lines[: header.macro_line_index]
        + [f" F  {header.alpha:.17e}\n"]
        + lines[header.qgrid_line_index :]
    )
    target.write_text("".join(output), encoding="utf-8")
    return target


__all__ = [
    "AMU_RY",
    "Q2RFormatError",
    "Q2RHeader",
    "QELatticeError",
    "qe_lattice_from_ibrav",
    "read_q2r_header",
    "read_second_order_qe_matrix",
    "read_third_d3q",
    "strip_q2r_nac",
]


class QELatticeError(ValueError):
    """A q2r Bravais-lattice header is malformed or unsupported."""


def _positive(value: float, name: str, ibrav: int) -> None:
    """Validate a positive ``celldm`` parameter with lattice context."""
    if value <= 0.0:
        raise QELatticeError(f"ibrav={ibrav}: {name} must be positive, got {value}")


def _cosine(value: float, name: str, ibrav: int) -> None:
    """Validate a ``celldm`` cosine whose magnitude must be below one."""
    if abs(value) >= 1.0:
        raise QELatticeError(f"ibrav={ibrav}: |{name}| must be < 1, got {value}")


def qe_lattice_from_ibrav(
    ibrav: int,
    celldm: Sequence[float] | _FLOAT,
    *,
    at_columns: _FLOAT | None = None,
) -> tuple[_FLOAT, float]:
    """Construct QE direct lattice vectors as rows in bohr.

    This implementation follows the crystallographic definitions published in
    Quantum ESPRESSO's ``INPUT_PW`` documentation. It is an independent Python
    implementation: every case first constructs dimensionless vectors in units
    of ``a = celldm(1)`` and the common epilogue applies that scale and validates
    the volume. See https://www.quantum-espresso.org/Doc/INPUT_PW.html#ibrav.

    ``at_columns`` is required for ``ibrav=0`` because formatted q2r files store
    those explicit vectors as columns in units of ``celldm(1)``.
    """
    parameters = np.asarray(celldm, dtype=np.float64)
    if parameters.shape != (6,) or not np.isfinite(parameters).all():
        raise QELatticeError("celldm must be six finite values")

    alat = float(parameters[0])
    _positive(alat, "celldm(1)", ibrav)

    if ibrav == 0:
        if at_columns is None:
            raise QELatticeError("ibrav=0 requires q2r lattice vectors")
        columns = np.asarray(at_columns, dtype=np.float64)
        if columns.shape != (3, 3) or not np.isfinite(columns).all():
            raise QELatticeError("ibrav=0 vectors must be a finite 3x3 matrix")
        dimensionless_rows = columns.T
    else:
        b_over_a = float(parameters[1])
        c_over_a = float(parameters[2])
        if ibrav in {8, 9, -9, 91, 10, 11, 12, -12, 13, -13, 14}:
            _positive(b_over_a, "celldm(2)", ibrav)
        if ibrav in {4, 6, 7, 8, 9, -9, 91, 10, 11, 12, -12, 13, -13, 14}:
            _positive(c_over_a, "celldm(3)", ibrav)

        half = 0.5
        match ibrav:
            case 1:  # simple cubic
                dimensionless_rows = np.eye(3)
            case 2:  # face-centred cubic
                dimensionless_rows = half * np.array(
                    [[-1.0, 0.0, 1.0], [0.0, 1.0, 1.0], [-1.0, 1.0, 0.0]]
                )
            case 3:  # body-centred cubic, conventional QE orientation
                dimensionless_rows = half * np.array(
                    [[1.0, 1.0, 1.0], [-1.0, 1.0, 1.0], [-1.0, -1.0, 1.0]]
                )
            case -3:  # body-centred cubic, symmetric-axis orientation
                dimensionless_rows = half * np.array(
                    [[-1.0, 1.0, 1.0], [1.0, -1.0, 1.0], [1.0, 1.0, -1.0]]
                )
            case 4:  # primitive hexagonal
                dimensionless_rows = np.array(
                    [[1.0, 0.0, 0.0], [-half, np.sqrt(3.0) * half, 0.0], [0.0, 0.0, c_over_a]]
                )
            case 5 | -5:  # rhombohedral; the sign selects the threefold axis
                cos_gamma = float(parameters[3])
                if not -0.5 < cos_gamma < 1.0:
                    raise QELatticeError(
                        f"ibrav={ibrav}: celldm(4) must lie in (-0.5, 1)"
                    )
                tx = np.sqrt((1.0 - cos_gamma) / 2.0)
                ty = np.sqrt((1.0 - cos_gamma) / 6.0)
                tz = np.sqrt((1.0 + 2.0 * cos_gamma) / 3.0)
                if ibrav == 5:
                    dimensionless_rows = np.array(
                        [[tx, -ty, tz], [0.0, 2.0 * ty, tz], [-tx, -ty, tz]]
                    )
                else:
                    scale = 1.0 / np.sqrt(3.0)
                    diagonal = tz - 2.0 * np.sqrt(2.0) * ty
                    off_diagonal = tz + np.sqrt(2.0) * ty
                    dimensionless_rows = scale * np.array(
                        [
                            [diagonal, off_diagonal, off_diagonal],
                            [off_diagonal, diagonal, off_diagonal],
                            [off_diagonal, off_diagonal, diagonal],
                        ]
                    )
            case 6:  # primitive tetragonal
                dimensionless_rows = np.diag([1.0, 1.0, c_over_a])
            case 7:  # body-centred tetragonal
                dimensionless_rows = half * np.array(
                    [
                        [1.0, -1.0, c_over_a],
                        [1.0, 1.0, c_over_a],
                        [-1.0, -1.0, c_over_a],
                    ]
                )
            case 8:  # primitive orthorhombic
                dimensionless_rows = np.diag([1.0, b_over_a, c_over_a])
            case 9:  # C-centred orthorhombic
                dimensionless_rows = np.array(
                    [[half, half * b_over_a, 0.0], [-half, half * b_over_a, 0.0], [0.0, 0.0, c_over_a]]
                )
            case -9:  # alternate C-centred orthorhombic orientation
                dimensionless_rows = np.array(
                    [[half, -half * b_over_a, 0.0], [half, half * b_over_a, 0.0], [0.0, 0.0, c_over_a]]
                )
            case 91:  # A-centred orthorhombic
                dimensionless_rows = np.array(
                    [
                        [1.0, 0.0, 0.0],
                        [0.0, half * b_over_a, -half * c_over_a],
                        [0.0, half * b_over_a, half * c_over_a],
                    ]
                )
            case 10:  # face-centred orthorhombic
                dimensionless_rows = half * np.array(
                    [[1.0, 0.0, c_over_a], [1.0, b_over_a, 0.0], [0.0, b_over_a, c_over_a]]
                )
            case 11:  # body-centred orthorhombic
                dimensionless_rows = half * np.array(
                    [
                        [1.0, b_over_a, c_over_a],
                        [-1.0, b_over_a, c_over_a],
                        [-1.0, -b_over_a, c_over_a],
                    ]
                )
            case 12:  # primitive monoclinic, unique axis c
                cos_ab = float(parameters[3])
                _cosine(cos_ab, "celldm(4)", ibrav)
                dimensionless_rows = np.array(
                    [
                        [1.0, 0.0, 0.0],
                        [b_over_a * cos_ab, b_over_a * np.sqrt(1.0 - cos_ab**2), 0.0],
                        [0.0, 0.0, c_over_a],
                    ]
                )
            case -12:  # primitive monoclinic, unique axis b
                cos_ac = float(parameters[4])
                _cosine(cos_ac, "celldm(5)", ibrav)
                dimensionless_rows = np.array(
                    [
                        [1.0, 0.0, 0.0],
                        [0.0, b_over_a, 0.0],
                        [c_over_a * cos_ac, 0.0, c_over_a * np.sqrt(1.0 - cos_ac**2)],
                    ]
                )
            case 13:  # base-centred monoclinic, unique axis c
                cos_ab = float(parameters[3])
                _cosine(cos_ab, "celldm(4)", ibrav)
                dimensionless_rows = np.array(
                    [
                        [half, 0.0, -half * c_over_a],
                        [b_over_a * cos_ab, b_over_a * np.sqrt(1.0 - cos_ab**2), 0.0],
                        [half, 0.0, half * c_over_a],
                    ]
                )
            case -13:  # base-centred monoclinic, unique axis b (QE >= 6.4.1)
                cos_ac = float(parameters[4])
                _cosine(cos_ac, "celldm(5)", ibrav)
                dimensionless_rows = np.array(
                    [
                        [half, half * b_over_a, 0.0],
                        [-half, half * b_over_a, 0.0],
                        [c_over_a * cos_ac, 0.0, c_over_a * np.sqrt(1.0 - cos_ac**2)],
                    ]
                )
            case 14:  # triclinic
                cos_bc, cos_ac, cos_ab = map(float, parameters[3:6])
                _cosine(cos_bc, "celldm(4)", ibrav)
                _cosine(cos_ac, "celldm(5)", ibrav)
                _cosine(cos_ab, "celldm(6)", ibrav)
                sin_ab = np.sqrt(1.0 - cos_ab**2)
                determinant_factor = (
                    1.0
                    + 2.0 * cos_bc * cos_ac * cos_ab
                    - cos_bc**2
                    - cos_ac**2
                    - cos_ab**2
                )
                if determinant_factor <= 0.0:
                    raise QELatticeError("ibrav=14 celldm values do not define a real cell")
                dimensionless_rows = np.array(
                    [
                        [1.0, 0.0, 0.0],
                        [b_over_a * cos_ab, b_over_a * sin_ab, 0.0],
                        [
                            c_over_a * cos_ac,
                            c_over_a * (cos_bc - cos_ac * cos_ab) / sin_ab,
                            c_over_a * np.sqrt(determinant_factor) / sin_ab,
                        ],
                    ]
                )
            case _:
                raise QELatticeError(
                    f"unsupported/nonexistent Quantum ESPRESSO ibrav={ibrav}"
                )

    rows = np.asarray(dimensionless_rows * alat, dtype=np.float64)
    volume = float(abs(np.linalg.det(rows)))
    if volume < 1e-14:
        raise QELatticeError(f"ibrav={ibrav} generated a singular lattice")
    return rows, volume
