"""External ShengBTE ground truth for the bundled Si IFC fixtures.

The retained files were generated by official ShengBTE revision
``b0d209068239c37fc86d2021efda131ad854f1c1``. The VASP route validates the
complete IFC2/IFC3 transport path. The QE harmonic check explicitly selects
the Wigner--Seitz convention implemented by ShengBTE's ``phonon_espresso``;
it must not be read as an assertion about QE ``matdyn.x`` off-mesh behavior.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import pytest

from kaldo.conductivity import Conductivity
from kaldo.forceconstants import ForceConstants
from kaldo.phonons import Phonons


TEST_ROOT = Path(__file__).resolve().parent
REFERENCE_ROOT = TEST_ROOT / "data" / "input" / "shengbte-si-reference"


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _shengbte_harmonic(case: str):
    folder = REFERENCE_ROOT / case / "reference"
    qpoints_full = np.loadtxt(folder / "BTE.qpoints_full")
    omega_irreducible = np.atleast_2d(np.loadtxt(folder / "BTE.omega"))
    irreducible_ids = qpoints_full[:, 1].astype(int) - 1
    # ShengBTE changes q first and band second in this flat file: the q index
    # is the fast index, so transpose from (band, q, xyz) to (q, band, xyz).
    velocity = np.loadtxt(folder / "BTE.v_full").reshape(
        6, qpoints_full.shape[0], 3
    ).transpose(1, 0, 2)
    return (
        qpoints_full[:, 2:5],
        omega_irreducible[irreducible_ids],
        velocity,
    )


def _q_indices(phonons: Phonons, qpoints: np.ndarray) -> np.ndarray:
    kaldo_qpoints = phonons._reciprocal_grid.fractional_points
    indices = []
    for qpoint in qpoints:
        delta = np.mod(kaldo_qpoints - qpoint + 0.5, 1.0) - 0.5
        matches = np.flatnonzero(np.linalg.norm(delta, axis=1) < 1.0e-9)
        assert matches.size == 1
        indices.append(matches[0])
    return np.asarray(indices)


@pytest.fixture(scope="module")
def vasp_phonons():
    forceconstants = ForceConstants.from_folder(
        folder=str(TEST_ROOT / "si-crystal" / "vasp"),
        supercell=(5, 5, 5),
        third_supercell=(5, 5, 5),
        format="vasp-sheng",
    )
    return Phonons(
        forceconstants=forceconstants,
        kpts=(3, 3, 3),
        temperature=300.0,
        third_bandwidth=None,
        broadening_kernel="shengbte",
        include_isotopes=False,
        is_nac=False,
        ifc_interpolation="auto",
        storage="memory",
        n_workers=1,
        use_q_symmetry=False,
    )


@pytest.fixture(scope="module")
def qe_ws_phonons():
    forceconstants = ForceConstants.from_folder(
        folder=str(TEST_ROOT / "si-crystal" / "qe"),
        supercell=(3, 3, 3),
        third_supercell=(3, 3, 3),
        format="qe-sheng",
    )
    return Phonons(
        forceconstants=forceconstants,
        kpts=(3, 3, 3),
        temperature=300.0,
        include_isotopes=False,
        is_nac=False,
        ifc_interpolation="wigner-seitz",
        storage="memory",
        n_workers=1,
        use_q_symmetry=False,
    )


def test_shengbte_reference_manifest_hashes_every_retained_file():
    """The manifest locks both source IFCs and every selected raw result."""
    manifest = json.loads((REFERENCE_ROOT / "manifest.json").read_text())
    assert manifest["shengbte"]["commit"] == (
        "b0d209068239c37fc86d2021efda131ad854f1c1"
    )
    for case_data in manifest["cases"].values():
        for relative, expected in case_data["sources"].items():
            candidate = REFERENCE_ROOT / relative
            if not candidate.exists():
                candidate = TEST_ROOT / relative
            assert _sha256(candidate) == expected
        for relative, expected in case_data["results"].items():
            assert _sha256(REFERENCE_ROOT / relative) == expected


@pytest.mark.parametrize(
    ("case", "fixture_name", "frequency_atol", "velocity_atol"),
    [
        ("vasp", "vasp_phonons", 9.0e-4, 0.16),
        ("qe", "qe_ws_phonons", 2.1e-3, 0.21),
    ],
)
def test_full_grid_harmonic_data_matches_shengbte(
    case, fixture_name, frequency_atol, velocity_atol, request
):
    """Match all 27 q points without relying on cubic high-symmetry lines."""
    phonons = request.getfixturevalue(fixture_name)
    qpoints, omega, velocity = _shengbte_harmonic(case)
    indices = _q_indices(phonons, qpoints)

    # ShengBTE omega is rad/ps; kALDo frequency is cycles/ps. Its velocity is
    # km/s = nm/ps, whereas kALDo reports angstrom/ps. Sorted mode values avoid
    # arbitrary bases inside exactly degenerate subspaces.
    np.testing.assert_allclose(
        np.sort(2.0 * np.pi * phonons.frequency[indices], axis=1),
        np.sort(omega, axis=1),
        rtol=0.0,
        atol=frequency_atol,
    )
    np.testing.assert_allclose(
        np.sort(np.linalg.norm(phonons.velocity[indices], axis=2), axis=1),
        np.sort(np.linalg.norm(10.0 * velocity, axis=2), axis=1),
        rtol=0.0,
        atol=velocity_atol,
    )


def test_vasp_anharmonic_rates_match_shengbte(vasp_phonons):
    """The native adaptive kernel reproduces every nonzero irreducible rate."""
    folder = REFERENCE_ROOT / "vasp" / "reference"
    qpoints = np.loadtxt(folder / "BTE.qpoints")[:, 3:6]
    indices = _q_indices(vasp_phonons, qpoints)
    raw = np.loadtxt(folder / "T300K" / "BTE.w_anharmonic")
    reference = raw.reshape(6, qpoints.shape[0], 2).transpose(1, 0, 2)[:, :, 1]
    actual = vasp_phonons.anharmonic_bandwidth[indices]

    np.testing.assert_allclose(
        np.sort(actual, axis=1),
        np.sort(reference, axis=1),
        rtol=1.4e-2,
        atol=1.0e-10,
    )


def test_vasp_rta_scalar_matches_shengbte(vasp_phonons):
    """Pin the user-visible transport result after mode-level validation."""
    reference_row = np.loadtxt(
        REFERENCE_ROOT / "vasp" / "reference" / "BTE.KappaTensorVsT_RTA"
    )
    reference_tensor = reference_row[1:].reshape(3, 3)
    actual_tensor = Conductivity(
        phonons=vasp_phonons,
        method="rta",
        storage="memory",
    ).conductivity.sum(axis=0)
    np.testing.assert_allclose(
        np.trace(actual_tensor) / 3.0,
        np.trace(reference_tensor) / 3.0,
        rtol=2.0e-2,
        atol=0.0,
    )
