"""External ShengBTE ground truth for the bundled Si IFC fixtures.

The retained files were generated by official ShengBTE revision
``b0d209068239c37fc86d2021efda131ad854f1c1``. The VASP route validates the
complete IFC2/IFC3 transport path. The QE route checks automatic q2r
Wigner--Seitz interpolation and literal ShengBTE IFC3 translations. Separate
QE 7.6 matdyn tests remain the authority for QE-specific off-mesh behavior.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import numpy as np
import pytest

from kaldo.conductivity import Conductivity
from kaldo.forceconstants import ForceConstants
from kaldo.interfaces.qe_io import read_q2r_header
from kaldo.phonons import Phonons

TEST_ROOT = Path(__file__).resolve().parent
REFERENCE_ROOT = TEST_ROOT / "data" / "input" / "shengbte-si-reference"
# ShengBTE derives this natural-isotope average from Src/data.f90 instead of
# using the mass written in espresso.ifc2. Correcting that known convention
# difference keeps the external comparison about IFC interpolation rather
# than relaxing its tolerance for a 5.51e-3 amu mass mismatch.
SHENGBTE_SI_MASS_AMU = 28.0855099896


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _shengbte_harmonic(case: str):
    folder = REFERENCE_ROOT / case / "reference"
    qpoints_full = np.loadtxt(folder / "BTE.qpoints_full")
    omega_irreducible = np.atleast_2d(np.loadtxt(folder / "BTE.omega"))
    irreducible_ids = qpoints_full[:, 1].astype(int) - 1
    # ShengBTE changes q first and band second in this flat file: the q index
    # is the fast index, so transpose from (band, q, xyz) to (q, band, xyz).
    velocity = (
        np.loadtxt(folder / "BTE.v_full")
        .reshape(6, qpoints_full.shape[0], 3)
        .transpose(1, 0, 2)
    )
    return (
        qpoints_full[:, 2:5],
        omega_irreducible[irreducible_ids],
        velocity,
    )


def _q_indices(phonons: Phonons, qpoints: np.ndarray) -> np.ndarray:
    kaldo_qpoints = phonons._reciprocal_grid.fractional_points
    indices = []
    for qpoint in qpoints:
        delta = np.mod(kaldo_qpoints - qpoint + 0.5, 1.0) - 0.5
        matches = np.flatnonzero(np.linalg.norm(delta, axis=1) < 1.0e-9)
        assert matches.size == 1
        indices.append(matches[0])
    return np.asarray(indices)


@pytest.fixture(scope="module")
def vasp_phonons():
    forceconstants = ForceConstants.from_folder(
        folder=str(TEST_ROOT / "si-crystal" / "vasp"),
        supercell=(5, 5, 5),
        third_supercell=(5, 5, 5),
        format="vasp-sheng",
    )
    return Phonons(
        forceconstants=forceconstants,
        kpts=(3, 3, 3),
        temperature=300.0,
        third_bandwidth=None,
        broadening_kernel="shengbte",
        include_isotopes=False,
        is_nac=False,
        ifc_interpolation="auto",
        storage="memory",
        n_workers=1,
        use_q_symmetry=False,
    )


@pytest.fixture(scope="module")
def qe_phonons():
    # Load from the reference's OWN retained inputs, not the si-crystal/qe
    # fixture: the pinned ShengBTE run consumed a FORCE_CONSTANTS_3RD written
    # in the standard diamond basis together with a CONTROL in the x-mirrored
    # (POSCAR) basis, an internally inconsistent pairing that has since been
    # corrected in the fixture (see test_crystal_qe_vasp.py). This test's
    # contract is same-inputs-same-outputs against the pinned upstream
    # revision, so it must keep running on the exact bytes ShengBTE saw.
    forceconstants = ForceConstants.from_folder(
        folder=str(REFERENCE_ROOT / "qe"),
        supercell=(3, 3, 3),
        third_supercell=(3, 3, 3),
        format="qe-sheng",
    )
    return Phonons(
        forceconstants=forceconstants,
        kpts=(3, 3, 3),
        temperature=300.0,
        third_bandwidth=None,
        broadening_kernel="shengbte",
        include_isotopes=False,
        is_nac=False,
        ifc_interpolation="auto",
        storage="memory",
        n_workers=1,
        use_q_symmetry=False,
    )


def test_shengbte_reference_manifest_hashes_every_retained_file():
    """The manifest locks both source IFCs and every selected raw result."""
    manifest = json.loads((REFERENCE_ROOT / "manifest.json").read_text())
    assert manifest["shengbte"]["commit"] == (
        "b0d209068239c37fc86d2021efda131ad854f1c1"
    )
    for case_data in manifest["cases"].values():
        for relative, expected in case_data["sources"].items():
            candidate = REFERENCE_ROOT / relative
            if not candidate.exists():
                candidate = TEST_ROOT / relative
            assert _sha256(candidate) == expected
        for relative, expected in case_data["results"].items():
            assert _sha256(REFERENCE_ROOT / relative) == expected


@pytest.mark.parametrize(
    ("case", "fixture_name", "frequency_atol", "velocity_atol"),
    [
        ("vasp", "vasp_phonons", 9.0e-4, 0.16),
        ("qe", "qe_phonons", 2.1e-3, 0.21),
    ],
)
def test_full_grid_harmonic_data_matches_shengbte(
    case, fixture_name, frequency_atol, velocity_atol, request
):
    """Match all 27 q points without relying on cubic high-symmetry lines."""
    phonons = request.getfixturevalue(fixture_name)
    qpoints, omega, velocity = _shengbte_harmonic(case)
    indices = _q_indices(phonons, qpoints)

    if case == "qe":
        q2r_mass = read_q2r_header(
            TEST_ROOT / "si-crystal" / "qe" / "espresso.ifc2"
        ).atom_masses_amu[0]
        mass_scale = np.sqrt(SHENGBTE_SI_MASS_AMU / q2r_mass)
        omega = omega * mass_scale
        velocity = velocity * mass_scale

    # ShengBTE omega is rad/ps; kALDo frequency is cycles/ps. Its velocity is
    # km/s = nm/ps, whereas kALDo reports angstrom/ps. Sorted mode values avoid
    # arbitrary bases inside exactly degenerate subspaces.
    np.testing.assert_allclose(
        np.sort(2.0 * np.pi * phonons.frequency[indices], axis=1),
        np.sort(omega, axis=1),
        rtol=0.0,
        atol=frequency_atol,
    )
    np.testing.assert_allclose(
        np.sort(np.linalg.norm(phonons.velocity[indices], axis=2), axis=1),
        np.sort(np.linalg.norm(10.0 * velocity, axis=2), axis=1),
        rtol=0.0,
        atol=velocity_atol,
    )


def test_vasp_anharmonic_rates_match_shengbte(vasp_phonons):
    """The native adaptive kernel reproduces every nonzero irreducible rate."""
    folder = REFERENCE_ROOT / "vasp" / "reference"
    qpoints = np.loadtxt(folder / "BTE.qpoints")[:, 3:6]
    indices = _q_indices(vasp_phonons, qpoints)
    raw = np.loadtxt(folder / "T300K" / "BTE.w_anharmonic")
    reference = raw.reshape(6, qpoints.shape[0], 2).transpose(1, 0, 2)[:, :, 1]
    actual = vasp_phonons.anharmonic_bandwidth[indices]

    # rtol calibrated cross-platform: macOS arm64 BLAS shifts individual
    # sorted rates by up to 1.6% against the pinned ShengBTE reference
    # (linux x86: <=1.4%). Physical disagreement between codes would be
    # tens of percent, so 2.5e-2 stays a real check.
    np.testing.assert_allclose(
        np.sort(actual, axis=1),
        np.sort(reference, axis=1),
        rtol=2.5e-2,
        atol=1.0e-10,
    )


def test_qe_anharmonic_rates_track_shengbte_without_lost_blocks(qe_phonons):
    """Literal QE/Sheng IFC3 keeps the full external rate distribution."""
    folder = REFERENCE_ROOT / "qe" / "reference"
    qpoints = np.loadtxt(folder / "BTE.qpoints")[:, 3:6]
    indices = _q_indices(qe_phonons, qpoints)
    raw = np.loadtxt(folder / "T300K" / "BTE.w_anharmonic")
    reference = raw.reshape(6, qpoints.shape[0], 2).transpose(1, 0, 2)[:, :, 1]
    actual = qe_phonons.anharmonic_bandwidth[indices]

    reference = np.sort(reference, axis=1)
    actual = np.sort(actual, axis=1)
    mask = reference > 1.0e-10
    ratios = actual[mask] / reference[mask]
    # The two codes use independently implemented adaptive kernels. Individual
    # coarse-mesh modes differ by up to about 15%, but the median rate agrees
    # to 1e-4. Pin both facts so a dropped translation block cannot hide in an
    # aggregate conductivity.
    # Cross-platform margin (see the vasp rate test above): 6e-3 covers the
    # arm64 eigenbasis drift on the median ratio while any lost-block
    # regression moves it by percent-level amounts.
    np.testing.assert_allclose(np.median(ratios), 1.0, rtol=6.0e-3, atol=0.0)
    # Per-mode window: macOS arm64 (Accelerate) reaches 1.164 on the worst
    # coarse-mesh mode; a lost translation block shifts per-mode rates by
    # tens of percent, so 1.18 stays discriminating.
    assert np.min(ratios) > 0.85
    assert np.max(ratios) < 1.18


def test_vasp_rta_tensor_matches_shengbte(vasp_phonons):
    """Pin the diagonal tensor and bound finite-mesh symmetry leakage."""
    reference_row = np.loadtxt(
        REFERENCE_ROOT / "vasp" / "reference" / "BTE.KappaTensorVsT_RTA"
    )
    reference_tensor = reference_row[1:].reshape(3, 3)
    actual_tensor = Conductivity(
        phonons=vasp_phonons,
        method="rta",
        storage="memory",
    ).conductivity.sum(axis=0)
    np.testing.assert_allclose(
        np.diag(actual_tensor), np.diag(reference_tensor), rtol=2.0e-2, atol=0.0
    )
    off_diagonal = actual_tensor - np.diag(np.diag(actual_tensor))
    # ShengBTE symmetry-reduces the cubic mesh and reports exact zeros. kALDo
    # deliberately evaluates the full unsymmetrized grid here because the
    # literal IFC3 support is larger than the periodic supercell. Require the
    # residual Cartesian leakage to stay below the same two-percent scale.
    assert np.max(np.abs(off_diagonal)) < 0.02 * np.mean(np.diag(reference_tensor))
