"""
Tests for the pheasy force-constant importer (format='pheasy').

Unit tests build synthetic files in tmp_path following pheasy's exact output
conventions (see kaldo/interfaces/pheasy_io.py docstring). Integration tests
use the committed differential fixtures under si-crystal/pheasy and
mgo/pheasy, generated by their make_fixture.py from the trusted hiphive and
qe-d3q routes.
"""
from pathlib import Path

import numpy as np
import pytest

POSCAR_2ATOM = (
    "Si\n1.0\n3.0 0.0 0.0\n0.0 3.0 0.0\n0.0 0.0 3.0\nSi\n2\n"
    "Direct\n0.0 0.0 0.0\n0.5 0.5 0.5\n"
)


def _write_poscar(folder):
    (Path(folder) / "POSCAR").write_text(POSCAR_2ATOM)


def test_structure_missing_raises(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_structure
    with pytest.raises(FileNotFoundError, match=r"POSCAR.*cell\.in|cell\.in.*POSCAR"):
        read_pheasy_structure(str(tmp_path))


def test_structure_reads_poscar(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_structure
    _write_poscar(tmp_path)
    atoms = read_pheasy_structure(str(tmp_path))
    assert atoms.positions.shape == (2, 3)
    assert atoms.get_chemical_symbols() == ["Si", "Si"]


def test_born_charges_roundtrip(tmp_path):
    from kaldo.interfaces.pheasy_io import read_born_charges
    dielectric = np.diag([2.5, 2.5, 2.5])
    born_0 = np.diag([1.1, 1.1, 1.1])
    born_1 = np.diag([-1.1, -1.1, -1.1])
    rows = np.vstack([dielectric, born_0, born_1])
    np.savetxt(tmp_path / "born.fmt", rows)
    charges = read_born_charges(str(tmp_path), n_atoms=2)
    assert charges.shape == (3, 3, 3)
    np.testing.assert_allclose(charges[0], dielectric, atol=1e-12)
    np.testing.assert_allclose(charges[1], born_0, atol=1e-12)
    np.testing.assert_allclose(charges[2], born_1, atol=1e-12)


def test_born_charges_wrong_count_raises(tmp_path):
    from kaldo.interfaces.pheasy_io import read_born_charges
    np.savetxt(tmp_path / "born.fmt", np.ones((8, 3)))  # 9 rows expected for 2 atoms
    with pytest.raises(ValueError, match="born.fmt"):
        read_born_charges(str(tmp_path), n_atoms=2)


def test_pheasy_cell_map_is_exact_on_asymmetric_grid():
    from kaldo.interfaces.pheasy_io import _pheasy_cell_to_kaldo_id
    d0, d1, d2 = 2, 3, 4
    mapping = _pheasy_cell_to_kaldo_id((d0, d1, d2))
    assert mapping.shape == (24,)
    assert sorted(mapping.tolist()) == list(range(24))
    for c in range(24):
        ox = c % d0
        oy = (c // d0) % d1
        oz = c // (d0 * d1)
        kaldo_c_order_id = ox * (d1 * d2) + oy * d2 + oz
        assert mapping[c] == kaldo_c_order_id


def test_supercell_order_check_accepts_pheasy_order(tmp_path, caplog):
    import ase.io
    from ase import Atoms
    from kaldo.interfaces.pheasy_io import check_pheasy_supercell_order
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    d0, d1, d2 = 2, 1, 1
    n_cells = d0 * d1 * d2
    scaled = atoms.get_scaled_positions()
    positions, numbers = [], []
    for i in range(len(atoms)):
        for c in range(n_cells):
            ox, oy, oz = c % d0, (c // d0) % d1, c // (d0 * d1)
            positions.append((scaled[i] + np.array([ox, oy, oz])) / np.array([d0, d1, d2]))
            numbers.append(atoms.numbers[i])
    sposcar = Atoms(numbers=numbers, scaled_positions=positions,
                    cell=np.array(atoms.cell) * np.array([[d0], [d1], [d2]]), pbc=True)
    ase.io.write(tmp_path / "SPOSCAR", sposcar, format="vasp")
    check_pheasy_supercell_order(str(tmp_path), atoms, (d0, d1, d2))
    assert not [r for r in caplog.records if "pheasy supercell" in r.getMessage()
                or "atom order" in r.getMessage()]


def test_supercell_order_check_warns_on_cell_major_order(tmp_path, caplog):
    import ase.io
    from kaldo.interfaces.pheasy_io import check_pheasy_supercell_order
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    wrong = atoms * (2, 1, 1)  # ASE repeat is cell-major, not pheasy's atom-major
    ase.io.write(tmp_path / "SPOSCAR", wrong, format="vasp")
    check_pheasy_supercell_order(str(tmp_path), atoms, (2, 1, 1))
    assert [r for r in caplog.records if "atom order does not match" in r.getMessage()]


def test_supercell_order_check_noop_without_supercell_file(tmp_path, caplog):
    import ase.io
    from kaldo.interfaces.pheasy_io import check_pheasy_supercell_order
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    check_pheasy_supercell_order(str(tmp_path), atoms, (2, 1, 1))
    assert not caplog.records


# ---------------------------------------------------------------------------
# Helper writers: emit kaldo-layout FC2 in pheasy's exact FORCE_CONSTANTS
# format (also reused by later tasks). `value` has kaldo shape
# (1, n_uc, 3, n_rep, n_uc, 3) with replicas ordered by Grid(supercell, 'C').
# ---------------------------------------------------------------------------

def _kaldo_id_to_pheasy_c(supercell):
    from kaldo.grid import Grid
    d0, d1, d2 = supercell
    offsets = Grid((d0, d1, d2), order="C").grid(is_wrapping=False)
    return np.array([int(ox + oy * d0 + oz * d0 * d1) for (ox, oy, oz) in offsets])


def _write_fc2_text(path, value, supercell, row_style="pmap", full=False):
    d0, d1, d2 = supercell
    n_cells = d0 * d1 * d2
    n_uc = value.shape[1]
    n_sc = n_uc * n_cells
    to_c = _kaldo_id_to_pheasy_c(supercell)
    c_to_id = np.argsort(to_c)
    n_rows = n_sc if full else n_uc
    with open(path, "w") as fd:
        fd.write(f"{n_rows:>5d}{n_sc:5d}\n")
        for row in range(n_rows):
            i_uc, ci = (row // n_cells, row % n_cells) if full else (row, 0)
            for col in range(n_sc):
                j_uc, cj = col // n_cells, col % n_cells
                if full:
                    label = row + 1
                elif row_style == "pmap":
                    label = i_uc * n_cells + 1
                else:
                    label = i_uc + 1
                fd.write(f"{label:5d}{col + 1:5d}\n")
                oxi, oyi, ozi = ci % d0, (ci // d0) % d1, ci // (d0 * d1)
                oxj, oyj, ozj = cj % d0, (cj // d0) % d1, cj // (d0 * d1)
                rel_c = ((oxj - oxi) % d0) + ((oyj - oyi) % d1) * d0 + ((ozj - ozi) % d2) * d0 * d1
                block = value[0, i_uc, :, c_to_id[rel_c], j_uc, :]
                for alpha in range(3):
                    fd.write("".join(f"{x:25.15f}" for x in block[alpha]) + "\n")


def _random_fc2(n_uc, supercell, seed=0):
    rng = np.random.default_rng(seed)
    n_cells = supercell[0] * supercell[1] * supercell[2]
    return rng.standard_normal((1, n_uc, 3, n_cells, n_uc, 3))


def test_fc2_text_roundtrip_places_every_block(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    supercell = (2, 1, 1)
    value = _random_fc2(2, supercell)
    _write_fc2_text(tmp_path / "FORCE_CONSTANTS", value, supercell)
    loaded = read_pheasy_second(str(tmp_path), atoms, supercell)
    np.testing.assert_allclose(loaded, value, atol=1e-12)


def test_fc2_text_direct_row_labels_equivalent(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    supercell = (2, 1, 1)
    value = _random_fc2(2, supercell)
    _write_fc2_text(tmp_path / "FORCE_CONSTANTS", value, supercell, row_style="direct")
    loaded = read_pheasy_second(str(tmp_path), atoms, supercell)
    np.testing.assert_allclose(loaded, value, atol=1e-12)


def test_fc2_full_equals_compact(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    supercell = (2, 1, 1)
    value = _random_fc2(2, supercell)
    _write_fc2_text(tmp_path / "FORCE_CONSTANTS", value, supercell, full=True)
    loaded = read_pheasy_second(str(tmp_path), atoms, supercell)
    np.testing.assert_allclose(loaded, value, atol=1e-12)


def test_fc2_full_ignores_non_central_rows(tmp_path):
    """Rows outside the central cell are redundant by translation; corrupting them must not change the load."""
    import ase.io
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    supercell = (2, 1, 1)
    n_cells = 2
    value = _random_fc2(2, supercell, seed=7)
    path = tmp_path / "FORCE_CONSTANTS"
    _write_fc2_text(path, value, supercell, full=True)
    lines = path.read_text().splitlines()
    poisoned = [lines[0]]
    idx = 1
    while idx < len(lines):
        header = lines[idx]
        block = lines[idx + 1: idx + 4]
        if (int(header.split()[0]) - 1) % n_cells != 0:
            block = ["".join(f"{9999.0:25.15f}" for _ in range(3))] * 3
        poisoned.append(header)
        poisoned.extend(block)
        idx += 4
    path.write_text("\n".join(poisoned) + "\n")
    loaded = read_pheasy_second(str(tmp_path), atoms, supercell)
    np.testing.assert_allclose(loaded, value, atol=1e-12)


def test_fc2_hdf5_full_shape_ignores_non_central_rows(tmp_path):
    import h5py
    import ase.io
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    supercell = (2, 1, 1)
    n_uc, n_cells = 2, 2
    n_sc = n_uc * n_cells
    value = _random_fc2(n_uc, supercell, seed=8)
    to_c = _kaldo_id_to_pheasy_c(supercell)
    full = np.full((n_sc, n_sc, 3, 3), 9999.0)
    for i in range(n_uc):
        for rep in range(n_cells):
            for j in range(n_uc):
                full[i * n_cells, j * n_cells + to_c[rep]] = value[0, i, :, rep, j, :]
    with h5py.File(tmp_path / "fc2.hdf5", "w") as fd:
        fd.create_dataset("fc2", data=full)
    loaded = read_pheasy_second(str(tmp_path), atoms, supercell)
    np.testing.assert_allclose(loaded, value, atol=1e-12)


def test_fc2_hdf5_equals_text(tmp_path):
    import h5py
    import ase.io
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    supercell = (2, 1, 1)
    n_uc, n_cells = 2, 2
    n_sc = n_uc * n_cells
    value = _random_fc2(n_uc, supercell)
    to_c = _kaldo_id_to_pheasy_c(supercell)
    ifc2 = np.zeros((n_uc, n_sc, 3, 3))
    for i in range(n_uc):
        for rep in range(n_cells):
            for j in range(n_uc):
                ifc2[i, j * n_cells + to_c[rep]] = value[0, i, :, rep, j, :]
    with h5py.File(tmp_path / "fc2.hdf5", "w") as fd:
        fd.create_dataset("fc2", data=ifc2)
    loaded = read_pheasy_second(str(tmp_path), atoms, supercell)
    np.testing.assert_allclose(loaded, value, atol=1e-12)


def test_fc2_header_supercell_mismatch_raises(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    value = _random_fc2(2, (2, 1, 1))
    _write_fc2_text(tmp_path / "FORCE_CONSTANTS", value, (2, 1, 1))
    with pytest.raises(ValueError, match="supercell"):
        read_pheasy_second(str(tmp_path), atoms, (3, 1, 1))


def test_fc2_unrecognized_row_labels_raise(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    lines = [f"{2:>5d}{4:5d}"]
    for row, col in [(5, c) for c in range(1, 5)] + [(6, c) for c in range(1, 5)]:
        lines.append(f"{row:5d}{col:5d}")
        lines += ["    0.0    0.0    0.0"] * 3
    (tmp_path / "FORCE_CONSTANTS").write_text("\n".join(lines) + "\n")
    with pytest.raises(ValueError, match="row indices"):
        read_pheasy_second(str(tmp_path), atoms, (2, 1, 1))


def test_fc2_files_missing_raise(tmp_path):
    from kaldo.interfaces.pheasy_io import read_pheasy_second
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    with pytest.raises(FileNotFoundError, match=r"FORCE_CONSTANTS.*fc2\.hdf5|fc2\.hdf5.*FORCE_CONSTANTS"):
        read_pheasy_second(str(tmp_path), atoms, (1, 1, 1))


# ---------------------------------------------------------------------------
# SecondOrder.load / from_folder dispatch
# ---------------------------------------------------------------------------

def _make_pheasy_second_folder(tmp_path, supercell=(2, 1, 1), with_born=False):
    import ase.io
    _write_poscar(tmp_path)
    atoms = ase.io.read(tmp_path / "POSCAR", format="vasp")
    value = _random_fc2(2, supercell)
    _write_fc2_text(tmp_path / "FORCE_CONSTANTS", value, supercell)
    if with_born:
        rows = np.vstack([np.diag([2.5, 2.5, 2.5]), np.diag([1.1, 1.1, 1.1]), np.diag([-1.1, -1.1, -1.1])])
        np.savetxt(tmp_path / "born.fmt", rows)
    return atoms, value


def test_second_order_load_pheasy(tmp_path):
    from kaldo.observables.secondorder import SecondOrder
    _, value = _make_pheasy_second_folder(tmp_path)
    second = SecondOrder.load(folder=str(tmp_path), supercell=(2, 1, 1), format="pheasy")
    np.testing.assert_allclose(second.value, value, atol=1e-12)
    assert second._direct_grid.order == "C"


def test_from_folder_pheasy_only_second_with_born(tmp_path):
    from kaldo.forceconstants import ForceConstants
    _make_pheasy_second_folder(tmp_path, with_born=True)
    fc = ForceConstants.from_folder(str(tmp_path), supercell=(2, 1, 1), format="pheasy", only_second=True)
    # `third` is a lazy property that always materializes an empty ThirdOrder on access
    # (pre-existing behavior across every format, see ForceConstants.third); `_third` is the
    # unmaterialized attribute set directly from from_folder and is the real "was it loaded" signal.
    assert fc._third is None
    np.testing.assert_allclose(fc.atoms.info["dielectric"], np.diag([2.5, 2.5, 2.5]), atol=1e-12)
    np.testing.assert_allclose(fc.atoms.get_array("charges")[0], np.diag([1.1, 1.1, 1.1]), atol=1e-12)


def test_from_folder_pheasy_without_born_has_no_nac(tmp_path):
    from kaldo.forceconstants import ForceConstants
    _make_pheasy_second_folder(tmp_path, with_born=False)
    fc = ForceConstants.from_folder(str(tmp_path), supercell=(2, 1, 1), format="pheasy", only_second=True)
    assert "dielectric" not in fc.atoms.info


def test_second_order_pheasy_rejects_nondiagonal_supercell_matrix(tmp_path):
    from kaldo.observables.secondorder import SecondOrder
    _make_pheasy_second_folder(tmp_path)
    non_diagonal = np.array([[2, 1, 0], [0, 1, 0], [0, 0, 1]])
    with pytest.raises(ValueError, match="diagonal"):
        SecondOrder.load(folder=str(tmp_path), supercell=(2, 1, 1), format="pheasy",
                         supercell_matrix=non_diagonal)
